esphome:
  name: ${deviceid}
  friendly_name: ${devicename}

external_components:
  - source:
      type: local
      path: components

esp8266:
  board: esp12e

logger:
  # ESP8266 only - disable serial port logging, as the HeatPump component
  # needs the sole hardware UART on the ESP8266
  baud_rate: 0

uart:
  - id: ac_serial
    tx_pin: ${uart_tx_pin}
    rx_pin: ${uart_rx_pin}
    baud_rate: 9600
    parity: EVEN

sensor:
  - id: temperature_sensor
    platform: homeassistant
    internal: true
    entity_id: ${temperature_sensor_entity_id}
  - platform: toshiba_controller
    outdoor_temperature:
      name: Outdoor Temperature
    fcu_air_temp:
      name: fcuAirTemp
    fcu_setpoint:
      name: fcuSetpoint
    fcu_tc_temp:
      name: fcuTcTemp
    fcu_tcj_temp:
      name: fcuTcjTemp
    fcu_fan_rpm:
      name: fcuFanRpm
    cdu_td_temp:
      name: cduTdTemp
    cdu_ts_temp:
      name: cduTsTemp
    cdu_te_temp:
      name: cduTeTemp
    cdu_load:
      name: cduLoad
    cdu_iac:
      name: cduIac
  - platform: uptime
    name: Uptime

switch:
  - platform: toshiba_controller
    internal_thermistor:
      name: Internal Thermistor
    ionizer:
      name: Ionizer

select:
  - platform: template
    name: Special Mode
    id: special_mode
    optimistic: true
    icon: mdi:star-circle-outline
    options:
      - "Standard"
      - "High Power"
      - "ECO"
      - "8 Degrees"
      - "Fireplace 1"
      - "Fireplace 2"
      - "Silent 1"
      - "Silent 2"
      - "Sleep Care"
      - "Floor"
      - "Comfort"
    on_value:
      - lambda: |-
          ((ToshibaController*)id(toshiba_ac))->set_special_mode_select(i);
  - platform: template
    name: Swing Mode
    id: swing_mode
    optimistic: true
    icon: mdi:arrow-up-down
    options:
      - "Off"
      - "Vertical"
      - "Horizontal"
      - "Vertical & Horizontal"
      - "Fixed 1"
      - "Fixed 2"
      - "Fixed 3"
      - "Fixed 4"
      - "Fixed 5"
    on_value:
      - lambda: |-
          ((ToshibaController*)id(toshiba_ac))->set_swing_mode_select(i);
  - platform: template
    name: Power Select
    id: power_select
    optimistic: true
    icon: mdi:power
    options:
      - "50%"
      - "75%"
      - "100%"
    on_value:
      - lambda: |-
          ((ToshibaController*)id(toshiba_ac))->set_power_select(i);


toshiba_controller:
  id: toshiba_ac
  name: ""
  uart_id: ac_serial
  temperature_sensor_id: temperature_sensor
  special_mode_select_id: special_mode
  swing_mode_select_id: swing_mode
  power_select_id: power_select
  smart_thermostat_multiplier: ${smart_thermostat_multiplier}
  disable_cooling_modes: ${disable_cooling_modes}
  smart_thermostat_runaway_protection: ${smart_thermostat_runaway_protection}
